---
title: "Alma Thomas Iris, Tulips, Jonquils, and Crocuses, 1969"
author: "Miles Ott"
date: "11/21/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(gifski)

library(tidyverse)
colors<-c("#234573", #darkest blue  = 1
          "#83352e", #dark red      = 2
          "#c5cac1", #pale green    = 3
          "#b58339", #dark orange   = 4
          "#5d808c", #jade green    = 5
          "#3c7c7c", #darker green  = 6
          "#6ea577", #minty green   = 7
          "#98c9ce", #sky blue      = 8
          "#a7648a", #deep lilac    = 9
          "#dfcc3e", #bright yellow = 10
          "#c4a939", #goldenrod     = 11
          "#6f364f", #burgandy      = 12
          "#484a74", #deep purple   = 13
          "#b79da1", #rosy pink     = 14
          "#638fb6", #medium blue   = 15
          "#F4F0DB"  #off white     = 16
          )



```



```{r}
random_shape<-function(color_shape, xmin, xmax, ymin, ymax, jitter){
  n.gon<-sample(c(6, 8, 10, 12),1)
  half<-n.gon/2
  x<-c(rep(xmin, half), rep(xmax,half)) 
  y<-c(seq(ymax, ymin, length=half), seq(ymin, ymax, length=half))
  x<-x+c(runif(half, -jitter*1.3, jitter), runif(half, -jitter, jitter*1.2))
  y<-y+runif(n.gon, -jitter, jitter)
  shape<-geom_polygon(
              aes(
                x=x,
                y=y,
               ),
              fill=colors[color_shape])
  return(list(shape))
}

```



```{r}

mycols<-matrix(rep(1, 31*49), ncol=49)
for(i in 1:49){
  j<-sample(1:31,1, replace=TRUE, prob =seq(.05, .01, length=31)/sum(seq(.01, .05, length=31)) )
  mycols[1:j, i]<-sample(2:15,1)
}
mcols<-c(mycols)



shapes<-data.frame(
  y.max.seq<-rep(seq(0,6, length = 31), 49),
  x.max.seq<-sort(rep(seq(0, 5, length =49), 31), decreasing =FALSE),
  x.min.seq<-x.max.seq-5/49,
  y.min.seq<-y.max.seq -6/31,
  cols<- mcols #sample (1:15, 31*49, replace=TRUE, prob=c(.7, rep(.3/14, 14)))
  )%>%
  purrr::pmap(., 
            ~random_shape(
              color_shape = ..5,
              xmin        = ..3, 
              xmax        = ..2,
              ymin        = ..4,
              ymax        = ..1,
              jitter      = .04)
            )
```




```{r}
g<-ggplot()+ theme(panel.background = element_rect(fill=colors[16], colour=colors[16]),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank())+
  shapes+
coord_fixed()+
  scale_x_continuous(limits = c(-.3,5.2), expand = c(0, 0)) +
  scale_y_continuous(limits = c(-.4,6.2), expand = c(0, 0))+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

g

tiff("iris_tulips_jonquils_crocuses_4.tiff", width =5, height =6, units='in', res=400)
g
dev.off()

```






